version: '3.8'

services:
  streamlit:
    build: 
      context: ..
      dockerfile: ./Streamlit/Dockerfile.streamlit  # Reference to your Streamlit Dockerfile
    ports:
      - "8501:8501"  # Expose Streamlit port
    container_name: streamlit_app
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: always
    tty: true
    entrypoint: ["/start.sh"]  # Streamlit entrypoint script

  ollama:
    build: 
      context: ..
      dockerfile: ./Streamlit/Dockerfile.ollama 
    ports:
        - 11434:11434
    
        #- ./ollama/ollama:/app/.ollama
        #- ./entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    #entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    entrypoint: ["/entrypoint.sh"]

